// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mcpserver.Model;

#nullable disable

namespace mcpserver.Migrations
{
    [DbContext(typeof(PGContext))]
    [Migration("20250622121843_Editcontract")]
    partial class Editcontract
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("mcpserver.Model.Entities.ContractEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ContractDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("contract_date");

                    b.Property<string>("ContractName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contract_name");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("m_contracts");
                });

            modelBuilder.Entity("mcpserver.Model.Entities.LotContractEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractEntityId")
                        .HasColumnType("integer")
                        .HasColumnName("ContractEntityId");

                    b.Property<DateTime>("LotDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lot_date");

                    b.Property<string>("LotName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lot_name");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ContractEntityId");

                    b.ToTable("m_lotcontract");
                });

            modelBuilder.Entity("mcpserver.Model.Entities.LotContractEntity", b =>
                {
                    b.HasOne("mcpserver.Model.Entities.ContractEntity", null)
                        .WithMany("LotContracts")
                        .HasForeignKey("ContractEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mcpserver.Model.Entities.ContractEntity", b =>
                {
                    b.Navigation("LotContracts");
                });
#pragma warning restore 612, 618
        }
    }
}
